### PR TITLE
switch order of proxyRequest and rewriteRequest

### PR DESCRIPTION
**Pull request by shaefner-usgs**
I don't know why, but the order is sometimes important for proxies to work properly. Switching the order of these resolved an issue w/ a proxy server that wasn't working for me w/o causing any adverse effects.

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
I recommend updating your proxies to expect the urls are already rewritten.  When rewrites are first they execute and change the urls before the proxy sees them.  This is by design.

Also, it is usually best to submit pull requests against the main repository, rather than an individual developer's fork; in this case https://github.com/usgs/hazdev-project-skeleton

**Comment by shaefner-usgs** [comment]
I tried switching the order of the rules and proxies arrays, but it still doesn't work (with the require calls in the orig. order).

Could you be more specific? How can I get this working w/o changing the order of the require calls? That's the only thing I've found that actually works.

https://github.com/shaefner-usgs/earthquake-netquakes/blob/master/gruntconfig/connect.js

**Comment by jmfee-usgs** [comment]
Remove MOUNT_PATH from the proxy:
https://github.com/shaefner-usgs/earthquake-netquakes/blob/master/gruntconfig/connect.js#L31


Rewrites will remove the MOUNT_PATH, then Proxy will forward requests starting with /data

**Comment by shaefner-usgs** [comment]
Removed MOUNT_PAHT and it still doesn't work with the require statements in the orig order.

**Comment by jmfee-usgs** [comment]
I still recommend keeping the /data proxy independent of the MOUNT_PATH, which is configurable (and just happens to be set to /monitoring/netquakes).  If you want the proxy to follow mount path, you can add a rewrite to the proxy rule; if you don't you can hard code the '/monitoring/netquakes/data/' rewrite target...  I suspect this seems like overkill (rewrite to remove MOUNT_PATH, proxy to readd MOUNT_PATH).  We're looking into using an apache container environment so we only have to maintain the one pre-install path...

I also recommend adding the accept-encoding and host headers, as these help avoid gzip compression issues.

https://github.com/shaefner-usgs/earthquake-netquakes/blob/master/gruntconfig/connect.js#L30
```
    {
      context: '/data', // data on dev server
      host: config.ini.DATA_HOST,
      port: 80,
      headers: {
      	'accept-encoding': 'identity',
      	host: config.ini.DATA_HOST
      }
      rewrite: [
      	'^/data': MOUNT_PATH + '/data'
      ]
    },
```

grunt-connect-proxy docs are at https://www.npmjs.com/package/grunt-connect-proxy if you'd like to read more

**Pull request closed without merging**
